# these settings will control minecart flight.
# The speed of the cart while in flight is multiplied by vector
# with X/Z coordinates being the horizontal and Y being the vertical modifier.
speed:
    # this controls the rate at which the minecart slows down horizontally.
    # NOTE the minecart will still not travel faster than 8 m/s so horizontal 
    # velocity mod > 10 or so won't do much.
    horizontal: 1.1
    # this controls how fast the minecart will fall while in flight.
    # NOTE Minecarts still fall even with vertical of zero, just very slowly.
    vertical: 0.5

# If true, then you will not take fall damage in a minecart.
prevent_damage: false


## Use this to configure what happens when a minecart is empty or you exit it.
empty_speed:
    # If enabled is not set, ignore this section.
    enabled: false

    # Set horizontal/vertical speeds.
    horizontal: 0.95
    vertical: 0.95
